LOAD DATA INFILE 'Employees.csv' INTO TABLE Employees 
  IGNORE 1 LINES
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n';

LOAD DATA INFILE 'Suppliers.csv' INTO TABLE Suppliers 
  IGNORE 1 LINES
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n';

LOAD DATA INFILE 'Products.csv' INTO TABLE Products
  IGNORE 1 LINES
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n';

LOAD DATA INFILE 'Provided_By.csv' INTO TABLE Provided_By
  IGNORE 1 LINES
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\n';